asm_decor/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

web/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("project/", views.project, name="project"),
    path("service/", views.service, name="service"),
    path("update/", views.update, name="update"),
    path("career/", views.career, name="career"),
    path("contact/", views.contact, name="contact"),
]

web/models.py
from django.db import models
from django.utils.safestring import mark_safe

# Create your models here.


STATUS_CHOICHES = [
    ("", "Services "),
    ("Architectural Design", "Architectural Design"),
    ("Interior Design and Fit-out Works", "Interior Design and Fit-out Works"),
    ("3D Visualization and Graphics", "3D Visualization and Graphics"),
    ("Gypsum/Plaster Board/Plastering", "Gypsum/Plaster Board/Plastering"),
    ("Masonry, Tiling", "Masonry, Tiling"),
    ("Joinery/Carpentry", "Joinery/Carpentry"),
    ("Glazing Works", "Glazing Works"), 
]

class Contact(models.Model):
    services = models.CharField(
        max_length=50, choices=STATUS_CHOICHES, null=True, blank=True
    )    
    name=models.CharField(max_length=100)
    email=models.EmailField(max_length=254)
    message=models.TextField()

    def __str__(self):
        return self.name   


class Service(models.Model):

    ICON_CHOICES = (
        ('icon flaticon-houses', 'icon flaticon houses'),
        ('icon flaticon-living-room', 'icon flaticon living room'),
    )
    icon = models.CharField(max_length=100, choices=ICON_CHOICES)

    bgimage = models.ImageField(upload_to='photos')
    title = models.CharField(max_length=100)
    paragraph = models.TextField()
    paragraphread = models.TextField()
    
    def admin_photo(self):
        return mark_safe('<img src="{}" width="50" />'.format(self.bgimage.url))
    admin_photo.short_description = 'Image'
    admin_photo.allow_tags = True


    def __str__(self):
        return self.title
    

class Update(models.Model):
    image = models.ImageField(upload_to='photos')
    admin=models.CharField( max_length=50)
    date=models.DateTimeField(auto_now=False, auto_now_add=False)
    title = models.CharField(max_length=100)
    # paragraph = models.TextField()
    # paragraphread = models.TextField()
    
    def admin_photo(self):
        return mark_safe('<img src="{}" width="50" />'.format(self.image.url))
    admin_photo.short_description = 'Image'
    admin_photo.allow_tags = True


    def __str__(self):
        return self.title    
    

class Category(models.Model):  
    name=models.CharField(max_length=50)


    def __str__(self):
        return self.name     


class Project(models.Model):
    image = models.ImageField(upload_to='photos')
    title = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE , blank=True ,null=True)

    
    def admin_photo(self):
        return mark_safe('<img src="{}" width="50" />'.format(self.image.url))
    admin_photo.short_description = 'Image'
    admin_photo.allow_tags = True


    def __str__(self):
        return self.title   


class Career(models.Model):
    fullname=models.CharField(max_length=50)
    email=models.EmailField(max_length=254)
    number = models.CharField(max_length=254)
    coverletter = models.TextField()
    cv = models.FileField(upload_to="career/cv/")

    def __str__(self):
        return self.fullname       


class Testimonial(models.Model):
    name=models.CharField(max_length=50)
    image = models.ImageField(upload_to='photos')
    jobrole=models.CharField(max_length=254)
    paragraph = models.TextField()

    def __str__(self):
        return self.name               

web/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import EmailInput
from django.forms.widgets import NumberInput
from django.forms.widgets import Textarea
from django.forms.widgets import TextInput
from .models import Contact,Career


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

        widgets = {
            "service": forms.Select(
                attrs={"class": "form-group", "placeholder": "services"}
            ),
            "name": TextInput(
                attrs={"class": "form-group", "placeholder": "Enter your name"}
            ),
            "number": NumberInput(
                attrs={"class": "form-group", "placeholder": "Enter your Number"}
            ),
            "email": EmailInput(
                attrs={"class": "form-group", "placeholder": "Enter your Email"}
            ),
            "message": Textarea(
                attrs={"class": "form-group", "placeholder": "Message"}
            ),
        }


class CareerForm(ModelForm):
    class Meta:
        model = Career
        fields = ['fullname', 'email', 'number', 'coverletter', 'cv']
        cv = forms.FileField(required=True)
        # widgets = {
        #     "fullname": TextInput(
        #         attrs={"class": "form-group", "placeholder": "Enter your name"}
        #     ),
        #     "number": NumberInput(
        #         attrs={"class": "form-group", "placeholder": "Enter your Number"}
        #     ),
        #     "email": EmailInput(
        #         attrs={"class": "form-group", "placeholder": "Enter your Email"}
        #     ),
        #     "coverletter": Textarea(
        #         attrs={"class": "form-group", "placeholder": "Cover Letter"}
        #     ),
        #     "cv": TextInput(
        #         attrs={"class": "form-group","type":"file"}
        #     ),
        # }

templates/web/career.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}

<header class="pages-header bg-img valign parallaxie"
    data-background="https://archo.drupalet.com/demo/themes/drupalet_archo/img/05.jpg" data-overlay-dark="5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="cont text-center">
                    <h1>Career</h1>
                    <div class="path">
                        <a href="#0">Home</a><span>/</span><a href="#0" class="active">Career</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<br>
<section class="contact">
    <div class="container p-2 form">
        <form class="row g-3 ajax reload" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-md-6  p-2">
                <input type="text" name="fullname" placeholder=" Enter Your Full Name">
            </div>
            <div class="col-md-6  p-2">
                <input type="number" name="number" placeholder=" Enter Your Number">
            </div>
            <div class="col-md-12  p-2">
                <input type="email" name="email" placeholder=" Enter Your Email">
            </div>
            <div class="col-md-12  p-2">
                <textarea name="coverletter" id="id_coverletter" cols="30" rows="10"
                    placeholder=" coverletter"></textarea>
            </div>
            <div class="col-md-12  p-2">
                <input type="file" name="cv" id="id_cv">
            </div>
            <div class="col-12 p-2">
                <button type="submit" class="btn btn-danger">Submit</button>
            </div>
        </form>
    </div>
</section>


<br>

{% endblock content %}


{% block js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>
<script>
    var isLoading = false;
    $(document).on("submit", "form.ajax", function (e) {
        e.preventDefault();
        var $this = $(this),
            data = new FormData(this),
            action_url = $this.attr("action"),
            reset = $this.hasClass("reset"),
            reload = $this.hasClass("reload"),
            redirect = $this.hasClass("redirect"),
            redirect_url = $this.attr("data-redirect");

        if (!isLoading) {
            isLoading = true;
            $.ajax({
                url: action_url,
                type: "POST",
                data: data,
                cache: false,
                contentType: false,
                processData: false,
                dataType: "json",
                success: function (data) {
                    var status = data.status;
                    var title = data.title;
                    var message = data.message;
                    var pk = data.pk;
                    if (status == "true") {
                        title ? (title = title) : (title = "Success");
                        Swal.fire({
                            title: title,
                            html: message,
                            icon: "success",
                        }).then(function () {
                            redirect && (window.location.href = redirect_url), reload && window.location.reload(), reset && window.location.reset();
                        });
                    } else {
                        title ? (title = title) : (title = "An Error Occurred");
                        Swal.fire({
                            title: title,
                            html: message,
                            icon: "error",
                        });
                    }
                },
                error: function (data) {
                    var title = "An error occurred",
                        message = "something went wrong";
                    Swal.fire({
                        title: title,
                        html: message,
                        icon: "error",
                    });
                },
            }).then(function (response) {
                isLoading = false;
            });
        }
    });
</script>
{% endblock js %}

templates/web/contact.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}

<header class="pages-header bg-img valign parallaxie"
  data-background="https://archo.drupalet.com/demo/themes/drupalet_archo/img/05.jpg" data-overlay-dark="5">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="cont text-center">
          <h1>Contact</h1>
          <div class="path">
            <a href="#0">Home</a><span>/</span><a href="#0" class="active">Contact</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<section class="contact">
  <div class="info bg-gray pt-80 pb-80">
    <div class="container">
      <div class="row">

        <div class="col-lg-4">
          <div class="item"> <span class="icon pe-7s-phone"></span>
            <div class="cont">
              <h6 class="custom-font">Call Us</h6>
              <p><a href="tel:+97143511152"> +97 143 511 152</a></p>
              <!-- <p>+1 (000) 9876 54321</p> -->
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="item"> <span class="icon pe-7s-mail-open"></span>
            <div class="cont">
              <h6 class="custom-font">Email Us</h6>
              <p><a href="mailto:info@asmdecor.com">info@asmdecor.com</a></p>
              <!-- <p><a href="https://archo.drupalet.com/cdn-cgi/l/email-protection" class="__cf_email__"
                  data-cfemail="8edbfdebfce0efe3ebcef9ebecfde7faeba0ede1e3">[email&#160;protected]</a></p> -->
            </div>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="item"> <span class="icon pe-7s-map"></span>
            <div class="cont">
              <h6 class="custom-font">Address</h6>
              <p>P.o Box: 128241,
                Dubai- U.A.E</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6 map-box">
        <div class="map">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2481.593576568465!2d-0.1547216347983398!3d51.53901386621298!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48761ae62edd5771%3A0x27f2d823e2be0249!2sPrincess%20Rd%2C%20London%20NW1%208JR%2C%20UK!5e0!3m2!1sen!2s!4v1641457453899!5m2!1sen!2s"
            width="100%" height="600" style="border:0;" allowfullscreen loading="lazy"></iframe>

        </div>
      </div>
      <div class="col-lg-6 form">
        <div data-drupal-messages-fallback class="hidden"></div>
        <section id="block-drupalet-archo-content"
          class="section block drp-block block-system block-system-main-block no-title">
          <div class="container rm-container-class">
            <div class="row row-content" id="contact-form">
              <form class=" ajax reload" method="post">
                {% csrf_token %}

                {{form.name}}

                {{form.email}}

                {{form.services}}

                <br> <br>
                    
                {{form.message}}

                {% comment %} <button type="submit" id="edit-submit"
                  class="button button--primary js-form-submit form-submit text-center">Submit</button> {% endcomment %}
                <button type="submit" class="btn btn-danger">Submit</button>
              </form>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
</section>

{% endblock %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.15.3/dist/sweetalert2.all.min.js"></script>
<script>
  var isLoading = false;
  $(document).on("submit", "form.ajax", function (e) {
    e.preventDefault();
    var $this = $(this),
      data = new FormData(this),
      action_url = $this.attr("action"),
      reset = $this.hasClass("reset"),
      reload = $this.hasClass("reload"),
      redirect = $this.hasClass("redirect"),
      redirect_url = $this.attr("data-redirect");

    if (!isLoading) {
      isLoading = true;
      $.ajax({
        url: action_url,
        type: "POST",
        data: data,
        cache: false,
        contentType: false,
        processData: false,
        dataType: "json",
        success: function (data) {
          var status = data.status;
          var title = data.title;
          var message = data.message;
          var pk = data.pk;
          if (status == "true") {
            title ? (title = title) : (title = "Success");
            Swal.fire({
              title: title,
              html: message,
              icon: "success",
            }).then(function () {
              redirect && (window.location.href = redirect_url), reload && window.location.reload(), reset && window.location.reset();
            });
          } else {
            title ? (title = title) : (title = "An Error Occurred");
            Swal.fire({
              title: title,
              html: message,
              icon: "error",
            });
          }
        },
        error: function (data) {
          var title = "An error occurred",
            message = "something went wrong";
          Swal.fire({
            title: title,
            html: message,
            icon: "error",
          });
        },
      }).then(function (response) {
        isLoading = false;
      });
    }
  });
</script>
{% endblock js %}

templates/web/portfolio.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}

<header class="pages-header bg-img valign parallaxie"
  data-background="https://archo.drupalet.com/demo/themes/drupalet_archo/img/05.jpg" data-overlay-dark="5">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="cont text-center">
          <h1>Project</h1>
          <div class="path">
            <a href="#0">Home</a><span>/</span><a href="#0" class="active">Project</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<div data-drupal-messages-fallback class="hidden"></div>
<section id="block-drupalet-archo-content"
  class="section block drp-block block-system block-system-main-block no-title">
  <div class="container rm-container-class">
    <div class="row row-content">
      <article data-history-node-id="44" role="article" about="portfolio" typeof="schema:WebPage" class="article">
        <span property="schema:name" content="Portfolio" class="hidden"></span>
        <div>
        </div>
      </article>
    </div>
  </div>
</section>
<section
  class="views-element-container portfolio section-padding section block drp-block block-views block-views-blockportfolio-block-list-portfolio-style4 no-title"
  id="block-views-block-portfolio-block-list-portfolio-style4">
  <div class="container rm-container-class">
    <div class="row row-content">
      <div class="filtering text-center col-12 wow fadeInUp" data-wow-delay=".3s">
        <div class="filter bg-img bg-repeat" data-background="img/line-pattern1.png">
          <span data-filter="*" class="active">All</span>
          {% for ins in categories %}
          <span data-filter=".item-{{ins.id}}">{{ins.name}}</span>
          {% endfor %}
        </div>
      </div>

      <div class="gallery twsty inf-lit full-width">
        {% for project in projects %}
        <div class="items itemitem1 item-{{project.category.id}} three-column mt-50">
          <div class="item-img bg-img"
            data-background="{{project.image.url}}">
            <a href="#">
              <div class="item-img-overlay"></div>
            </a>
          </div>
          <div class="info mt-10">
            <h5> {{project.title}}</h5>
            <span>{{project.category}}</span>
          </div>
        </div>
        {% endfor %}

        <!-- <div class="items itemitem1 item5 item2 three-column mt-50">
            <div class="item-img bg-img" data-background="https://archo.drupalet.com/demo/sites/default/files/2021-12/02_1.jpg">
              <a href="node/19.html">
                <div class="item-img-overlay"></div>
              </a>
            </div>
            <div class="info mt-10">
              <h5>Fantastic interior</h5>
              <span>Web Design, Fashion, WordPress</span>
            </div>
          </div>
          <div class="items itemitem5 item3 item1 three-column mt-50">
            <div class="item-img bg-img" data-background="{% static 'web/imges/img/03_0.jpg' %}">
              <a href="node/18.html">
                <div class="item-img-overlay"></div>
              </a>
            </div>
            <div class="info mt-10">
              <h5>Startup Studio</h5>
              <span>Fashion, Photoshop, Web Design</span>
            </div>
          </div>
          <div class="items itemitem1 item4 item3 three-column mt-50">
            <div class="item-img bg-img" data-background="{% static 'web/imges/img/04_0.jpg' %}">
              <a href="node/17.html">
                <div class="item-img-overlay"></div>
              </a>
            </div>
            <div class="info mt-10">
              <h5>Luxury Villa2</h5>
              <span>Web Design, RESIDENTIAL, Photoshop</span>
            </div>
          </div>
          <div class="items itemitem1 item5 three-column mt-50">
            <div class="item-img bg-img" data-background="{% static 'web/imges/img/05.jpg' %}">
              <a href="node/16.html">
                <div class="item-img-overlay"></div>
              </a>
            </div>
            <div class="info mt-10">
              <h5>Creative Spaces</h5>
              <span>Web Design, Fashion</span>
            </div>
          </div>
          <div class="items itemitem1 item5 item2 three-column mt-50">
            <div class="item-img bg-img" data-background="{% static 'web/imges/img/06.jpg' %}">
              <a href="node/15.html">
                <div class="item-img-overlay"></div>
              </a>
            </div>
            <div class="info mt-10">
              <h5>Creative Agency</h5>
              <span>Web Design, Fashion, WordPress</span>
            </div>
          </div>
          <div class="items itemitem1 item14 item3 three-column mt-50">
            <div class="item-img bg-img" data-background="{% static 'web/imges/img/07.jpg' %}">
              <a href="node/14.html">
                <div class="item-img-overlay"></div>
              </a>
            </div>
            <div class="info mt-10">
              <h5>Fantastic interior</h5>
              <span>Web Design, cms, Photoshop</span>
            </div>
          </div>
          <div class="items itemitem1 item5 item4 three-column mt-50">
            <div class="item-img bg-img" data-background="{% static 'web/imges/img/08.jpg' %}">
              <a href="node/13.html">
                <div class="item-img-overlay"></div>
              </a>
            </div>
            <div class="info mt-10">
              <h5>Choose Your Dream</h5>
              <span>Web Design, Fashion, RESIDENTIAL</span>
            </div>
          </div>
          <div class="items itemitem1 item4 item3 three-column mt-50">
            <div class="item-img bg-img" data-background="{% static 'web/imges/img/09_0.jpg' %}">
              <a href="node/12.html">
                <div class="item-img-overlay"></div>
              </a>
            </div>
            <div class="info mt-10">
              <h5>Luxury Villa</h5>
              <span>Web Design, RESIDENTIAL, Photoshop</span>
            </div>
          </div>
          <div class="items itemitem1 item2 three-column mt-50">
            <div class="item-img bg-img" data-background="{% static 'web/imges/img/03.jpg' %}">
              <a href="node/11.html">
                <div class="item-img-overlay"></div>
              </a>
            </div>
            <div class="info mt-10">
              <h5>Luxury Villa</h5>
              <span>Web Design, WordPress</span>
            </div>
          </div>
          <div class="items itemitem1 item14 three-column mt-50">
            <div class="item-img bg-img" data-background="{% static 'web/imges/img/02.jpg' %}">
              <a href="node/10.html">
                <div class="item-img-overlay"></div>
              </a>
            </div>
            <div class="info mt-10">
              <h5>Creative Spaces</h5>
              <span>Web Design, cms</span>
            </div>
          </div> -->
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/web/services.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}

<header class="pages-header bg-img valign parallaxie"
    data-background="https://archo.drupalet.com/demo/themes/drupalet_archo/img/05.jpg" data-overlay-dark="5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="cont text-center">
                    <h1>Services</h1>
                    <div class="path">
                        <a href="#0">Home</a><span>/</span><a href="#0" class="active">Services</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>




<section
    class="views-element-container services section-padding bg-gray section block drp-block block-views block-views-blockservices-block-services-style1"
    id="block-views-block-services-block-services-style1" data-title="Our Services" data-sub-title="Best Features">
    <div class="container rm-container-class">
        <div class="section-head text-center">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <h6 class="custom-font wow fadeInDown subtitle-section" data-wow-delay=".3s"></h6>
                    <h4 class="playfont wow flipInX title-section" data-wow-delay=".5s">Our Services</h4>
                </div>
            </div>
        </div>
        <div class="row row-content service-gap">
            {% for service in services %}
            <div class="col-sm-12 col-lg-4">
                <div class="item-bx bg-img wow fadeInUp P-2" data-wow-delay=".5s"
                    data-background="{{service.bgimage.url}}"> <span class="{{service.icon}}"></span>
                    <h6 class="mb-20">{{service.title}}</h6>
                    <p>{{service.paragraph}}</p>
                    <a href="#" class="more custom-font mt-30">Read More</a>
                </div>
            </div>
            {% endfor %}

            <!-- <div class="col-lg-4">
                <div class="item-bx bg-img wow fadeInUp" data-wow-delay=".5s"
                    data-background="{% static 'web/images/img/2_9.jpg' %}"> <span
                        class="icon flaticon-living-room"></span>
                    <h6 class="mb-20">Masonry, Tiling</h6>
                    <p>Cras mollis turpis a ipsum ultes, nec cond imentum ipsum consequat.</p>
                    <a href="#" class="more custom-font mt-30">Read More</a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="item-bx bg-img wow fadeInUp" data-wow-delay=".5s"
                    data-background="{% static 'web/images/img/03_2.jpg' %}"> <span class="icon flaticon-houses"></span>
                    <h6 class="mb-20">Joinery/Carpentry</h6>
                    <p>Cras mollis turpis a ipsum ultes, nec cond imentum ipsum consequat.</p>
                    <a href="#" class="more custom-font mt-30">Read More</a>
                </div>
            </div>
        </div>
        <br>
        <div class="row row-content">
            <div class="col-lg-4">
                <div class="item-bx bg-img wow fadeInUp" data-wow-delay=".5s"
                    data-background="{% static 'web/images/img/03_2.jpg' %}"> <span class="icon flaticon-houses"></span>
                    <h6 class="mb-20">Glazing Works</h6>
                    <p>Cras mollis turpis a ipsum ultes, nec cond imentum ipsum consequat.</p>
                    <a href="#" class="more custom-font mt-30">Read More</a>
                </div>
            </div>
         -->
        </div>
    </div>
</section>




{% endblock content %}

templates/web/updates.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}

<header class="pages-header bg-img valign parallaxie"
    data-background="https://archo.drupalet.com/demo/themes/drupalet_archo/img/05.jpg" data-overlay-dark="5">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="cont text-center">
                    <h1>Updates & Blogs</h1>
                    <div class="path">
                        <a href="#0">Home</a><span>/</span><a href="#0" class="active">Updates & Blogs</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<section
    class="views-element-container blog-grid section-padding mb-50 section block drp-block block-views block-views-blockblog-block-style-1"
    id="block-views-block-blog-block-style-1" data-title="Our Blogs" data-sub-title="Latest News">
    <div class="container rm-container-class">
        <div class="section-head text-center">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8 col-sm-10">
                    <h6 class="custom-font wow fadeInDown subtitle-section" data-wow-delay=".3s"></h6>
                    <h4 class="playfont wow flipInX title-section" data-wow-delay=".5s">Blog style 1</h4>
                </div>
            </div>
        </div>
        <div class="row row-content">
            {% for update in updates %}
            <div class="col-lg-4">
                <div class="item wow fadeInUp md-mb50" data-wow-delay=".3s">
                    <div class="post-img">
                        <div class="img"> <img src="{{update.image.url}}" alt> </div>
                    </div>
                    <div class="cont">
                        <div class="info"> <a href="#0">admin</a> <a href="#0">01 Wed 2022</a> </div>
                        <h5 class="playfont"><a href="#">{{update.title}}</a> </h5>
                        <a href="#" class="more"> <span class="custom-font">Read More</span> </a>
                    </div>
                </div>
            </div>
            {% endfor %}

            <!-- <div class="col-lg-4">
      <div class="item wow fadeInUp md-mb50" data-wow-delay=".3s">
        <div class="post-img">
          <div class="img"> <img
              src="{% static 'web/sites/default/files/styles/image_802x590/public/2022-01/b41a78.jpg' %}" alt> </div>
        </div>
        <div class="cont">
          <div class="info"> <a href="#0">admin</a> <a href="#0">01 Wed 2022</a> </div>
          <h5 class="playfont"><a href="node/46.html">The main component of a healthy env for </a> </h5>
          <a href="node/46.html" class="more"> <span class="custom-font">Read More</span> </a>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="item wow fadeInUp md-mb50" data-wow-delay=".3s">
        <div class="post-img">
          <div class="img"> <img
              src="{% static 'web/sites/default/files/styles/image_802x590/public/2021-12/1_10a86d.jpg' %}" alt> </div>
        </div>
        <div class="cont">
          <div class="info"> <a href="#0">admin</a> <a href="#0">12 Fri 2021</a> </div>
          <h5 class="playfont"><a href="node/33.html">Five Things You Should Know About Modern Furniture.</a> </h5>
          <a href="node/33.html" class="more"> <span class="custom-font">Read More</span> </a>
        </div>
      </div>
    </div> -->
        </div>
    </div>
</section>

{% endblock content %}