asm_decor/urls.py
# Define urlpatterns in project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls", namespace="web")),
        path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
        path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "PROJECT Administration"
admin.site.site_title = "PROJECT Admin Portal"
admin.site.index_title = "Welcome to PROJECT Admin Portal"

web/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("project/", views.project, name="project"),
    path("service/", views.service, name="service"),
    path("update/", views.update, name="update"),
    path("career/", views.career, name="career"),
    path("contact/", views.contact, name="contact"),
]

templates/web/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr"
    prefix="content: http://purl.org/rss/1.0/modules/content/  dc: http://purl.org/dc/terms/  foaf: http://xmlns.com/foaf/0.1/  og: http://ogp.me/ns#  rdfs: http://www.w3.org/2000/01/rdf-schema#  schema: http://schema.org/  sioc: http://rdfs.org/sioc/ns#  sioct: http://rdfs.org/sioc/types#  skos: http://www.w3.org/2004/02/skos/core#  xsd: http://www.w3.org/2001/XMLSchema# ">
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->

<head>
    <meta charset="utf-8" />
    <meta name="Generator" content="Drupal 9 (https://www.drupal.org)" />
    <meta name="MobileOptimized" content="width" />
    <meta name="HandheldFriendly" content="true" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
        .logo-header .logo-header-inner img {
            max-width: 160px !important;
        }

        .logo-header .logo-header-inner img {
            max-height: 67px !important;
        }

        .logo-header .logo-header-inner img {
            margin: 0px 0px 0px 0px !important;
        }
    </style>
    <link rel="icon" href="https://www.asmdecor.com/favicon.png" type="image/vnd.microsoft.icon" />
    <link rel="canonical" href="" />
    <link rel="shortlink" href="node/2.html" />
    <title>ASM Decor</title>
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/ajax-progress.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/align.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/autocomplete-loading.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/fieldgroup.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/container-inline.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/clearfix.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/details.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/hidden.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/item-list.modulebad7.css' %}" />
    <link rel="stylesheet" media="all" href="{% static 'web/core/modules/system/css/components/js.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/nowrap.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/position-container.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/progress.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/reset-appearance.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/resize.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/sticky-header.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/system-status-counterbad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/system-status-report-countersbad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/system-status-report-general-infobad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/tabledrag.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/tablesort.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="{% static 'web/core/modules/system/css/components/tree-child.modulebad7.css' %}" />
    <link rel="stylesheet" media="all" href="{% static 'web/core/modules/views/css/views.modulebad7.css' %}" />
    <link rel="stylesheet" media="all"
        href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&amp;display=swap" />
    <link rel="stylesheet" media="all"
        href="https://fonts.googleapis.com/css?family=Teko:300,400,500,600,700&amp;display=swap" />
    <link rel="stylesheet" media="all"
        href="https://fonts.googleapis.com/css?family=Playfair+Display:400,500,600,700,800,900&amp;display=swap" />
    <link rel="stylesheet" media="all" href="{% static 'web/themes/drupalet_archo/css/pluginsbad7.css' %}" />
    <link rel="stylesheet" media="all" href="{% static 'web/themes/drupalet_archo/css/stylebad7.css' %}" />
    <link rel="stylesheet" media="all" href="{% static 'web/themes/drupalet_archo/css/updatebad7.css' %}" />
</head>

<body class="layout-no-sidebars page-main path-node node--type-page" data-spy="scroll" data-target=".scrolly"
    data-offset="50">

    <div id="preloader">
        <div class="loading-text">Loading</div>
    </div>

    {% include 'web/partials/header.html' %}
    {% block content %}
    {% endblock content %}
    {% include 'web/partials/footer.html' %}



    <script data-cfasync="false" src="{% static 'web/js/email-decode.min.js' %}"></script>
    <script
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUU5FZiF5WLFFfgIC1n64Zr0zfpQZjBBg&amp;callback=initMap&amp;v=weekly"
        async></script>
    <script>
        let map;

        function initMap() {
            map = new google.maps.Map(document.getElementById("map"), {
                center: { lat: 34.0937458, lng: 118.3614978 },
                zoom: 8,
            });
        }
    </script>
    <script type="application/json"
        data-drupal-selector="drupal-settings-json">{"path":{"baseUrl":"\/demo\/","scriptPath":null,"pathPrefix":"","currentPath":"node\/2","currentPathIsAdmin":false,"isFront":false,"currentLanguage":"en"},"pluralDelimiter":"\u0003","suppressDeprecationErrors":true,"ajaxTrustedUrl":{"\/demo\/search\/node":true},"user":{"uid":0,"permissionsHash":"5c5383c89f56074e42d8fa99aef20a862b1c4417d081a1194150a4c78f5e014d"}}</script>
    <script src="{% static 'web/core/assets/vendor/jquery/jquery.min45e0.js' %}?v=3.6.0"></script>
    <script src="{% static 'web/core/misc/drupalSettingsLoaderb9d7.js' %}?v=9.3.0"></script>
    <script src="{% static 'web/core/misc/drupalb9d7.js' %}?v=9.3.0"></script>
    <script src="{% static 'web/core/misc/drupal.initb9d7.js' %}?v=9.3.0"></script>
    <script src="{% static 'web/themes/drupalet_archo/js/jquery-3.0.0.minb9d7.js' %}?v=9.3.0"></script>
    <script src="{% static 'web/themes/drupalet_archo/js/jquery-migrate-3.0.0.minb9d7.js' %}?v=9.3.0"></script>
    <script src="{% static 'web/themes/drupalet_archo/js/pluginsb9d7.js' %}?v=9.3.0"></script>
    <script src="{% static 'web/themes/drupalet_archo/js/scriptsb9d7.js' %}?v=9.3.0"></script>
    <script src="{% static 'web/themes/drupalet_archo/js/mapb9d7.js' %}?v=9.3.0"></script>
    <script src="{% static 'web/themes/drupalet_archo/js/updateb9d7.js' %}?v=9.3.0"></script>

  {% block js %}
    
  {% endblock js %}
</body>

</html>

templates/web/partials/footer.html
{% load static %}
<style>
  #logo {
    height: 70px;
    width: 60px;
  }
</style>
<footer class="main-footer dark">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div id="block-archofooterfirst"
          class="block drp-block item fotcont block-block-content block-block-contente86023ef-b28f-43a8-a794-cf74989c8155 no-title">
          <div class="item abot">
            <div class="logo-footer mb-20">
              <a href="" class="logo">
                <img id="logo" alt="logo" data-entity-type="file"
                  data-entity-uuid="c016fc6e-4c18-41c0-9c48-115cb0741875" src="{% static 'web/images/logo2.png' %}"
                  width="50" height="20" loading="lazy" />
              </a>
            </div>
            <p>Our team takes over everything, from an idea and concept development to realization.</p>
            <div class="social-icon">
              <a href="#0"><i class="fab fa-facebook-f"></i></a>
              <a href="#0"><i class="fab fa-twitter"></i></a>
              <a href="#0"><i class="fab fa-behance"></i></a>
              <a href="#0"><i class="fab fa-pinterest-p"></i></a>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-2 offset-lg-1">
        <div id="block-archofootersecond"
          class="item usful-links block drp-block item fotcont block-block-content block-block-content52eb76c4-1798-4173-8a2e-3113e62dad01"
          data-title="USEFUL LINKS">
          <div class="fothead">
            <h6>QUILK LINK</h6>
          </div>
          <ul>
            <li><i class="fas fa-chevron-right"></i> <a href="{% url 'web:index' %}">Home</a></li>
            <li><i class="fas fa-chevron-right"></i> <a href="{% url 'web:about' %}">About Us</a></li>
            <li><i class="fas fa-chevron-right"></i> <a href="{% url 'web:project' %}">Projects</a></li>
            <li><i class="fas fa-chevron-right"></i> <a href="{% url 'web:service' %}">Services</a></li>
            <li><i class="fas fa-chevron-right"></i> <a href="{% url 'web:update' %}">Updates</a></li>
            <li><i class="fas fa-chevron-right"></i> <a href="{% url 'web:career' %}">Career</a></li>
            <li><i class="fas fa-chevron-right"></i> <a href="{% url 'web:contact' %}">Contact</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-2">
        <div id="block-archofooterthird"
          class="fotcont block drp-block item block-block-content block-block-content3afe276b-5028-4957-971d-2f85a27eb6d1">
          <div class="fothead">
            <h6>CALL</h6>
          </div>
          <p><a href="tel:+97143511152"> +97 143 511 152</a></p>
          <!-- <p>+1(000)987654321</p> -->
        </div>
      </div>
      <div class="col-lg-2">
        <div id="block-archofooterfour"
          class="block drp-block item fotcont block-block-content block-block-contentf6b6500a-7576-4439-b1bf-1443cf0d4549">
          <div class="fothead">
            <h6>WRITE</h6>
          </div>
          <p><a href="mailto:info@asmdecor.com">info@asmdecor.com</a></p>
        </div>
      </div>
      <div class="col-lg-2">
        <div id="block-archofooterfive"
          class="block drp-block item fotcont block-block-content block-block-contentc18ccaa3-4d9f-4615-9ad7-f3d6d0b81b3b">
          <div class="fothead">
            <h6>VISIT</h6>
          </div>
          <p>P.o Box: 128241,
            Dubai- U.A.E</p>
        </div>
      </div>
    </div>
  </div>
  <div class="sub-footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <div class="text-left">
            <p>© 2023 Asm decor - Developed by <a href="https://gedexo.com/">Gedexo Technologies</a></p>
          </div>
        </div>
        <!-- <div class="col-lg-4">
          <div class="text-right">
            <span>Powered by <a href="https://www.drupal.org/">Drupal</a></span>
          </div>
        </div> -->
      </div>
    </div>
  </div>
</footer>

templates/web/partials/header.html
{% load static %}
<div class="progress-wrap cursor-pointer">
    <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
    </svg>
</div>

<div class="mouse-cursor cursor-outer"></div>
<div class="mouse-cursor cursor-inner"></div>
<a href="#main-content" class="visually-hidden focusable">
    Skip to main content
</a>

<nav class="navbar change navbar-expand-lg">
    <div class="container">

        <a class="logo" href="{% url 'web:index' %}"><img src="https://www.asmdecor.com/img/logo.png" alt="logo"
                class="logo-default"><img src="https://www.asmdecor.com/img/logo-small.png" alt="logo"
                class="scrolled-logo hide"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-bar"><i class="fas fa-bars"></i></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <nav role="navigation" aria-labelledby="block-drupalet-archo-main-menu-menu"
                id="block-drupalet-archo-main-menu">
                <h2 class="visually-hidden" id="block-drupalet-archo-main-menu-menu">Main navigation</h2>
                <ul class="navbar-nav ml-auto" id="main-menu" 0>
                    <li class="menu-item nav-item ">
                        <a href="{% url 'web:index' %}" class="nav-link {% if is_index %} active {% endif %}" data-drupal-link-system-path="node/4">HOME</a>
                    </li>
                    <li class="menu-item nav-item  rd-navbar-submenu" 0>
                        <a href="{% url 'web:about' %}" class="nav-link {% if is_about %} active {% endif %} " data-drupal-link-system-path="node/4">ABOUT US</a>
                    </li>
                    <li class="menu-item nav-item  rd-navbar-submenu" 0>
                        <a href="{% url 'web:project' %}" class="nav-link {% if is_project %} active {% endif %}" data-drupal-link-system-path="node/44">PROJECT</a>
                    </li>
                    <li class="menu-item nav-item  rd-navbar-submenu" 0>
                        <a href="{% url 'web:service' %}" class="nav-link {% if is_service %} active {% endif %}" data-drupal-link-system-path="node/44">SERVICES</a>
                    </li>
                    <li class="menu-item nav-item  rd-navbar-submenu" 0>
                        <a href="{% url 'web:update' %}" class="nav-link {% if is_update %} active {% endif %}" data-drupal-link-system-path="node/44">UPDATES</a>
                    </li>
                    <li class="menu-item nav-item  rd-navbar-submenu" 0>
                        <a href="{% url 'web:career' %}" class="nav-link {% if is_career %} active {% endif %}" data-drupal-link-system-path="node/44"> CAREER</a>
                    </li>
                    <li class="menu-item nav-item  rd-navbar-submenu" 0>
                        <a href="{% url 'web:contact' %}" class="nav-link {% if is_contact %} active {% endif %}" data-drupal-link-system-path="contact">CONTACT</a>
                    </li>
                </ul>
                 <!-- <li class="menu-item nav-item rd-navbar--has-dropdown rd-navbar-submenu" 0>
                        <a href="{% url 'web:contact' %}" class="nav-link" data-drupal-link-system-path="contact">CONTACT</a>
                    </li> -->
            </nav>
            <div class="social-icon">
                <a href="#0"><i class="fab fa-facebook-f"></i></a>
                <a href="#0"><i class="fab fa-twitter"></i></a>
                <a href="#0"><i class="fab fa-behance"></i></a>
            </div>
            <div class="search">
                <span class="icon pe-7s-search cursor-pointer"></span>
                <div class="search-form text-center custom-font">
                    <form action="" method="get" id="search-block-form"
                        accept-charset="UTF-8">
                        <div
                            class="js-form-item form-item js-form-type-search form-item-keys js-form-item-keys form-no-label">
                            <label for="edit-keys" class="visually-hidden">Search</label>
                            <input title="Enter the terms you wish to search for." data-drupal-selector="edit-keys"
                                type="search" id="edit-keys" name="keys" value size="15" maxlength="128"
                                class="form-search" />
                        </div>
                        <input class="search-form__submit button js-form-submit form-submit"
                            data-drupal-selector="edit-submit" type="submit" id="edit-submit" value="Search" />
                    </form>
                    <span class="close pe-7s-close cursor-pointer"></span>
                </div>
            </div>
        </div>
    </div>
</nav>